version: "3"

services:
  zookeeper:
    image: wurstmeister/zookeeper:latest
    container_name: zookeeper
    ports:
      - 2181:2181

  kafka:
    image: wurstmeister/kafka:latest
    container_name: kafka
    depends_on:
      - zookeeper
    ports:
      - 9092:9092
    environment:
      JMX_PORT: 8004
      KAFKA_ADVERTISED_HOST_NAME: "192.168.1.45"
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181