version: "3"

services:
    db:
        container_name: koic_db
        image: postgres:13.3-alpine
        ports:
            - 5432:5432
        volumes:
            - db:/var/lib/postgresql/data
        environment:
            - POSTGRES_USER=root
            - POSTGRES_DB=koic_detections
            - POSTGRES_PASSWORD=password
    api:
        container_name: koic_api
        build: .
        network_mode: "host"

volumes:
    db: